app = "inventario-pos"
primary_region = "iad"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.3"

[env]
  APP_NAME = "Inventario POS"
  APP_ENV = "production"
  APP_KEY = "base64:56ADYJNbFD6jOQ0ahKcq1NxLIFVQoDFaof2o7bsyA9E="
  APP_DEBUG = "false"
  APP_URL = "https://inventario-pos.fly.dev"

  LOG_CHANNEL = "stack"
  LOG_DEPRECATIONS_CHANNEL = "null"
  LOG_LEVEL = "error"

  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/var/lib/sqlite/inventario-pos.db"

  BROADCAST_DRIVER = "log"
  CACHE_DRIVER = "file"
  FILESYSTEM_DISK = "local"
  QUEUE_CONNECTION = "sync"
  SESSION_DRIVER = "file"
  SESSION_LIFETIME = "120"

  MEMCACHED_HOST = "127.0.0.1"

  REDIS_HOST = "127.0.0.1"
  REDIS_PASSWORD = "null"
  REDIS_PORT = "6379"

  MAIL_MAILER = "smtp"
  MAIL_HOST = "mailpit"
  MAIL_PORT = "1025"
  MAIL_USERNAME = "null"
  MAIL_PASSWORD = "null"
  MAIL_ENCRYPTION = "null"
  MAIL_FROM_ADDRESS = "hello@example.com"
  MAIL_FROM_NAME = "${APP_NAME}"

  AWS_ACCESS_KEY_ID = ""
  AWS_SECRET_ACCESS_KEY = ""
  AWS_DEFAULT_REGION = "us-east-1"
  AWS_BUCKET = ""
  AWS_USE_PATH_STYLE_ENDPOINT = "false"

  PUSHER_APP_ID = ""
  PUSHER_APP_KEY = ""
  PUSHER_APP_SECRET = ""
  PUSHER_HOST = ""
  PUSHER_PORT = "443"
  PUSHER_SCHEME = "https"
  PUSHER_APP_CLUSTER = "mt1"

  VITE_APP_NAME = "${APP_NAME}"
  VITE_PUSHER_APP_KEY = "${PUSHER_APP_KEY}"
  VITE_PUSHER_HOST = "${PUSHER_HOST}"
  VITE_PUSHER_PORT = "${PUSHER_PORT}"
  VITE_PUSHER_SCHEME = "${PUSHER_SCHEME}"
  VITE_PUSHER_APP_CLUSTER = "${PUSHER_APP_CLUSTER}"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "inventario_pos_data"
  destination = "/var/lib/sqlite"

[processes]
  app = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
